---

- name: Configure Nomad jobs
  gather_facts: false
  hosts:
    - nomad_clients
  run_once: true 
  tasks:
    - import_role:
        name: nomad-job
      vars:
        job: bunker
      tags: [system, storage, csi, bunker]
      
    - import_role:
        name: nomad-job
      vars:
        job: fundament
      tags: [system, storage, csi, fundament]
      
    - import_role:
        name: nomad-job
      vars:
        job: homebound
      tags: [system, storage, csi, homebound]
      
    - import_role:
        name: nomad-job
      vars:
        job: backup
      tags: [service, backup]
      
    - import_role:
        name: nomad-job
      vars:
        job: gitea
      tags: [service, dev, gitea]
    
    - import_role:
        name: nomad-job
      vars:
        job: scrypted
      tags: [service, smarthome, security, scrypted]
      
    # - import_role:
    #     name: nomad-job
    #   vars:
    #     job: 1password
    #   tags: [service, security, 1password ]
      
    - import_role:
        name: nomad-job
      vars:
        job: diun
      tags: [system, monitoring, diun]
      
    - import_role:
        name: nomad-job
      vars:
        job: grafana
      tags: [system, monitoring, grafana]
    
    - import_role:
        name: nomad-job
      vars:
        job: changedetection
      tags: [service, monitoring, changedetection ]
      
    - import_role:
        name: nomad-job
      vars:
        job: uptimekuma
      tags: [service, monitoring, uptimekuma ]
      
    - import_role:
        name: nomad-job
      vars:
        job: mqtt
      tags: [service, infra, smarthome, mqtt ]
      
    - import_role:
        name: nomad-job
      vars:
        job: homepage
      tags: [service, monitoring, dashboard, homepage]
      
    - import_role:
        name: nomad-job
      vars:
        job: teslamate
      tags: [service, smarthome, auto, teslamate]
    
    - import_role:
        name: nomad-job
      vars:
        job: loki
      tags: [service, monitoring, logs, loki]
      
    - import_role:
        name: nomad-job
      vars:
        job: promtail
      tags: [system, monitoring, logs, promtail]
      
    - import_role:
        name: nomad-job
      vars:
        job: prometheus
      tags: [service, monitoring, prometheus]
    
    - import_role:
        name: nomad-job
      vars:
        job: debug
      tags: [debug]
      
    - import_role:
        name: nomad-job
      vars:
        job: scratch-map
      tags: [service, scratch-map]
  
    - import_role:
        name: nomad-job
      vars:
        job: traefik
        # combined_tags: "{{ (traefik.default_tags | default([])) + (traefik.publish_tags | default([])) }}"
      tags: [ networking, traefik ]