---

- name: Configure Vault nodes
  gather_facts: true
  hosts:
    - vault_nodes
  tasks:
    ### Run Vault role
    - name: Run the Vault role
      include_role:
        name: vault-node
        
    ### Configure vault after startup
    - name: Run the post-startup configuration task
      include_role:
        name: vault-node
        tasks_from: post_configure.yml
      # Run only once, on at least one of the Vault nodes
      run_once: true
      
  tags: always

        