---
- name: Get all job files in job directory
  find:
    paths: "{{ playbook_dir }}/jobs/{{ job_name }}"
    patterns: "*.nomad"
  register: job_files
  delegate_to: 127.0.0.1

- name: Save job file for inspection if specified
  template:
    src: "{{ job_file.path }}"
    dest: jobs/{{ job_name }}/{{ job_file.path | basename }}
  with_items: "{{ query('list', job_files.files) }}"
  loop_control:
    loop_var: job_file
    label: "{{ job_file.path | basename }}"
  when: job_inspect is true

- name: Run Nomad jobs
  ansible.builtin.command:
    cmd: nomad job run -detach -
    stdin: "{{ lookup('template', job_file.path) }}"
  environment:
    NOMAD_TOKEN: "{{ nomad_root_token }}"
  register: job_output
  with_items: "{{ query('list', job_files.files) }}"
  loop_control:
    loop_var: job_file
    label: "{{ job_file.path | basename }}"